# Generated by Django 4.1.7 on 2023-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=FileNotFoundError),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=FileNotFoundError),
        ),
    ]
