# Generated by Django 4.1.7 on 2023-02-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_title', models.CharField(max_length=200)),
                ('Event_time', models.DateTimeField(auto_now_add=True)),
                ('Event_venue', models.CharField(max_length=100)),
                ('Conducting_Body', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('fav', models.BooleanField()),
            ],
        ),
    ]
