# Generated by Django 4.1.7 on 2023-02-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
