# Generated by Django 4.1.7 on 2023-02-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(default='static.default/', max_length=1000, upload_to='static/'),
        ),
    ]
