# Generated by Django 4.1.7 on 2023-02-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(default='static/default.jpg', max_length=1000, upload_to='static/'),
        ),
    ]
